# Generated by Django 3.1.5 on 2021-02-01 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=60)),
                ('intro', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=70)),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('charges', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.artist')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venues.venues')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='music_type',
            field=models.ManyToManyField(to='venues.Genre'),
        ),
    ]
